### ISSUE TITLE
계산기 과제 피드백

### ISSUE THREAD

**Issue by ssk910** [alsqja/Java-calculator#1]
# 1. Git

## 1.1. 커밋 메세지

우선, 커밋 메세지를 비교적 꼼꼼하게 작성해주신 것이 좋았습니다.
대부분의 회사에서는 아래 링크처럼 컨벤션을 적용하고 있으니 꼭 확인해주세요!

커밋 메세지는 사소해 보이지만, 생각보다 개발자들이 중요하게 여기는 부분입니다.
개발하다보면 시간이 없어서, 귀찮아서 제대로 작성하지 못하는 경우가 많은데 초기에 습관을 들이시면 큰 도움이 되실 것 같습니다.
나중에 나의 업무를 되돌아보거나 정리할 때, 이전 이력으로 되돌아가고 싶을 때 이 커밋 메세지가 굉장히 유용하니 아주 자세히는 아니더라도 풍부하게 커밋 메세지를 작성해주세요!

- [커밋 컨벤션의 중요성을 언급한 아티클](https://yozm.wishket.com/magazine/detail/1974/)
- [커밋 컨벤션에 대한 설명](https://hyunjun.kr/21)

## 1.2. .gitignore

- 프로젝트의 루트 디렉토리에 있는 .idea 폴더는 IDE인 IntelliJ Idea가 자체 설정을 위해 생성해 주는 폴더입니다. \
따라서 이 폴더는 .gitignore 파일에 추가해서 커밋되지 않도록 막으면 더욱 좋습니다.
  - 사용중인 OS, IDE 정보를 입력하면 이에 알맞는 .gitignore를 생성해주는 오픈소스도 있으니 한번 확인해보세요!
  - https://www.toptal.com/developers/gitignore

----

# 2. README 문서

README 문서를 markdown 문법에 html까지 섞어서 깔끔하게 잘 작성해 주셨습니다. 그리고 실행 결과 이미지까지 포함되어 매우 좋은 문서가 되었습니다.
이미 markdown 문법은 알고 계신 것 같아서 이에 대한 코멘트는 추가하지 않겠습니다.
그리고 이미 알고 계실지도 모르지만, 다른 오픈 소스 프로젝트의 README 문서를 참고해서 어떤 내용을 추가하면 좋은지 살펴봐도 좋습니다.
(이번 과제 프로젝트는 README를 자세하게 쓸 수 있을 만큼의 범위는 아니지만, 나중에 도움이 되셨으면 합니다)

예시:
- https://github.com/naver/fixture-monkey
- https://github.com/naver/ngrinder

----

# 3. 코드

## 3.1. Lv 1

- 예외 케이스도 잘 처리하셨고, 람다 형태의 switch 문법도 잘 사용하셨습니다.
- `scInput`이라는 변수는 연산자를 담는 역할이므로 연산자르 뜻하는 `operator`로 수정한다면 이름만 봐도 어떤 역할인지 쉽게 알 수 있습니다.
- 개행을 이용해서 단락처럼 코드를 좀 더 구분하여 읽기 쉽게 할 수 있습니다. 저는 아래와 같이 바꿔보았습니다.
  ```java
    public class App {
        public static void main(String[] args) {
            char operator;
            String scInput;
    
            do {
                Scanner sc = new Scanner(System.in);
    
                System.out.print("첫번째 양의 정수를 입력하세요: ");
                int firstNumber = sc.nextInt();
    
                System.out.print("두번째 양의 정수를 입력하세요: ");
                int secondNumber = sc.nextInt();
                sc.nextLine();  //  엔터 처리
    
                System.out.print("연산자를 입력하세요: ");
                scInput = sc.nextLine();
                operator = scInput.charAt(0);
    
                switch (operator) {
                    case '+' -> System.out.println(firstNumber + secondNumber);
                    case '-' -> System.out.println(firstNumber - secondNumber);
                    case '*' -> System.out.println(firstNumber * secondNumber);
                    case '/' -> {
                        if (secondNumber == 0) {
                            System.out.println("0으로 나눌 수 없습니다.");
                            continue;
                        }
                        System.out.println((double) firstNumber / secondNumber);
                    }
                    default -> System.out.println("지원하지 않는 연산자입니다.");
                }
            } while (!scInput.equals("exit"));
    
            System.out.println("프로그램 종료");
        }
    }
  ```
  굉장히 사소하지만, 코드를 어느 라인과 함께 묶느냐에 따라서 읽히는게 달라집니다.

## 3.2. Lv 2

몇 가지 기능은 요구사항에 없는 기능인 것으로 보아, 아마도 공부 목적으로 구현하신 것 같습니다.
나중에 Spring을 배우면서 활용할 기회가 많으니 지금은 요구사항만 충족되어도 충분합니다!

#### 3.2.1.1. `getAnswers()`, `setAnswers()` 메소드

이 메소드의 이름과 주석을 보아 `answers` 필드를 위한 getter & setter 메소드로 추측됩니다.
아시다시피 단순하게 getter는 필드를 리턴하는 것이고, setter는 필드를 초기화하는 메소드입니다.

그렇기 때문에 getter 메소드의 타입은 필드의 타입과 같아야 하고, setter 메소드의 파라미터의 타입은 필드와 같아야 합니다.
하지만, 구현하신 getter와 setter는 그렇지 않으므로 getter와 setter가 아닌 직접 정의한 또 다른 메소드로 볼 수 있습니다.
그래서 이름을 `getAnswersAsArray()`나 `setElemOfAnswers()` 등으로 수정한다면 다른 개발자로부터 일반적인 getter & setter와의 혼동을 피할 수 있어 보입니다.

#### 3.2.1.2. `calculate()` 메소드

이 메소드의 로직을 분석해보면 연산자를 사칙연산에 맞게 입력받으면 연산 후 결과를 `List`에 담은 후 리턴하고, 그렇지 않으면 0을 리턴하는 것으로 보입니다.
그렇다면 case 문에 모두 return을 넣지 않고, 아래처럼 수정할 수 있습니다.
```java
    public double calculate(int firstNum, int secondNum, String operator) {
        double answer;
        switch (operator) {
            case "+" -> answer = firstNum + secondNum;
            case "-" -> answer = firstNum - secondNum;
            case "*" -> answer = firstNum * secondNum;
            case "/" -> {
                if (secondNum == 0) {
                    throw new ArithmeticException("0으로 나눌 수 없습니다.");
                }

                answer = (double) firstNum / secondNum;
            }
            default -> {
                return 0;
            }
        }

        this.answers.add(answer);
        return answer;
    }
```

더 나아가서, 나눗셈의 경우 분모가 `0`일 때 `Exception`을 던져서 예외처리를 하고 있습니다.
사칙연산이 아닌 문자열을 입력받았을 때도 똑같이 `0`을 리턴하는 것보다 `Exception`을 던지는 것이 더욱 안전합니다.
그리고 마지막으로, 이 메소드에서는 `Exception`이 던져지므로 호출하는 곳에서 예외처리를 할 수 있도록 `throws` 키워드를 추가하면 더 좋습니다.
`javadoc` 주석도 추가해보았습니다.
```java
    /**
     * 입력 받은 값을 이용해 연산 후 결과를 리턴.
     *
     * @param firstNum  첫 번째 숫자
     * @param secondNum 두 번째 숫자
     * @param operator  연산자
     * @return 연산 결과
     * @throws ArithmeticException    나눗셈에서 분모가 0인 경우
     * @throws InputMismatchException 잘못된 연산자를 입력받은 경우
     */
    public double calculate(int firstNum, int secondNum, String operator) throws ArithmeticException, InputMismatchException {
        double answer;
        switch (operator) {
            case "+" -> answer = firstNum + secondNum;
            case "-" -> answer = firstNum - secondNum;
            case "*" -> answer = firstNum * secondNum;
            case "/" -> {
                if (secondNum == 0) {
                    throw new ArithmeticException("0으로 나눌 수 없습니다.");
                }

                answer = (double) firstNum / secondNum;
            }
            default -> throw new InputMismatchException("잘못된 연산자입니다.");
        }

        this.answers.add(answer);
        return answer;
    }
```
이렇게 하면, 이 메소드를 사용하는 입장에서는 더욱 안전하게 사용할 수 있습니다.

#### 3.2.2.1. `label`을 사용한 반복문

`label`은 분명히 존재하는 문법이지만 많이 사용되지 않습니다. 
프로그램의 실행 순서를 제어하기 때문에 적절하게 사용하면 문제가 없지만, 그렇지 못한 경우가 훨씬 많기 때문입니다.
다른 개발자들과 협업할 때 주의하시기 바랍니다.

#### 3.2.2.2. 변수 선언

아무래도 민범님께서 C언어를 배운 경험이 있으시다보니 C언어처럼 모든 변수를 최상단에서 사용하신 것 같습니다.
코드를 분석하는 입장에서 모든 변수 선언문을 상단에 모아놓으면 분석이 힘들어집니다.
변수가 선언된 문장을 봤어도, 금방 기억에서 사라진채로 다음 코드를 읽었을 때 이 변수의 타입이 무엇이었는지 잊어버리고 맙니다.
그래서 아래처럼 해당 변수가 처음 사용될 때 선언해주면 읽기 쉬워집니다. (스코프 때문에 상단에 선언해야 하는 경우는 제외)

```java
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Calculator calculator = new Calculator();
        label:
        while (true) {
            System.out.print("연산자를 입력하세요(exit: 종료, get: 결과 목록 출력, set: 결과 목록 수정, delete: 첫번째 결과 삭제): ");
            String operator = sc.nextLine();

            switch (operator) {
                case "exit":
                    break label;
                case "get":
                    double[] answers = calculator.getAnswers();
                    System.out.println(Arrays.toString(answers));
                    continue;
                case "set": {
                    int index;
                    double value;
                    System.out.print("수정하실 인덱스를 입력해주세요: ");
                    index = sc.nextInt();
                    System.out.print("수정하실 값을 입력해주세요: ");
                    value = sc.nextInt();
                    sc.nextLine();
                    double answer = calculator.setAnswers(index, value);
                    System.out.println(answer + " -> " + value + " 수정 완료!");
                    continue;
                }
                case "delete": {
                    double answer = calculator.deleteAnswer();
                    System.out.println(answer + " 삭제 완료");
                    continue;
                }
            }

            System.out.print("첫번째 양의 정수를 입력하세요: ");
            int firstNumber = sc.nextInt();

            System.out.print("두번째 양의 정수를 입력하세요: ");
            int secondNumber = sc.nextInt();

            sc.nextLine();  // 엔터 삭제

            double answerValue = calculator.calculate(firstNumber, secondNumber, operator);
            System.out.println("answer = " + answerValue);
        }
        System.out.println("프로그램 종료");
    }
```

그리고 아까와 마찬가지로, 개행으로 코드를 묶어보겠습니다.
```java
        Scanner sc = new Scanner(System.in);
        Calculator calculator = new Calculator();

        label:
        while (true) {
            System.out.print("연산자를 입력하세요(exit: 종료, get: 결과 목록 출력, set: 결과 목록 수정, delete: 첫번째 결과 삭제): ");
            String operator = sc.nextLine();

            switch (operator) {
                case "exit":
                    break label;
                case "get":
                    double[] answers = calculator.getAnswers();
                    System.out.println(Arrays.toString(answers));
                    continue;
                case "set": {
                    System.out.print("수정하실 인덱스를 입력해주세요: ");
                    int index = sc.nextInt();
                    
                    System.out.print("수정하실 값을 입력해주세요: ");
                    double value = sc.nextInt();
                    sc.nextLine();
                    
                    double answer = calculator.setAnswers(index, value);
                    System.out.println(answer + " -> " + value + " 수정 완료!");
                    continue;
                }
                case "delete": {
                    double answer = calculator.deleteAnswer();
                    System.out.println(answer + " 삭제 완료");
                    continue;
                }
            }

            System.out.print("첫번째 양의 정수를 입력하세요: ");
            int firstNumber = sc.nextInt();

            System.out.print("두번째 양의 정수를 입력하세요: ");
            int secondNumber = sc.nextInt();
            sc.nextLine();  // 엔터 삭제

            double answerValue = calculator.calculate(firstNumber, secondNumber, operator);
            System.out.println("answer = " + answerValue);
        }
        
        System.out.println("프로그램 종료");
    }
```

### 3.3.1. `ArithmeticCalculator` 클래스

`OperType` enum 클래스에서 필드를 추가하여 잘 활용하셨습니다. \
또한 `fromOperator()` 메소드에서 연산자에 해당하지 않으면 `Exception`을 던지는 부분도 좋습니다. \
위에서 언급한 것처럼 `throws` 키워드를 이용해 예외가 던져질 것을 나타내면 더 좋습니다.

#### 3.3.1.1. `operator` 필드

`ArithmeticCalculator` 클래스에는 연산자에 해당하는 `operator` 필드가 있습니다.
그리고 이 필드가 사용되는 곳은 `calculate()` 메소드 한 곳이며, 특별히 이 필드를 외부에서 접근할 것 같아 보이지 않습니다.
이렇게 객체가 이 필드에 대한 메모리를 추가로 갖도록 하는 것보다, 생명주기를 메소드 내부로 한정하는 것이 더 경제적입니다.
아래는 `operator` 필드를 지우고 그에 맞게 수정한 `calculate()` 메소드입니다.
```java
    public double calculate(T firstNumber, T secondNumber, String operator) {
        switch (OperType.fromOperator(operator)) {
            case ADD -> {
                this.answers.add(firstNumber.doubleValue() + secondNumber.doubleValue());
                return firstNumber.doubleValue() + secondNumber.doubleValue();
            }
            case SUBTRACT -> {
                this.answers.add(firstNumber.doubleValue() - secondNumber.doubleValue());
                return firstNumber.doubleValue() - secondNumber.doubleValue();
            }
            case MULTIPLY -> {
                this.answers.add(firstNumber.doubleValue() * secondNumber.doubleValue());
                return firstNumber.doubleValue() * secondNumber.doubleValue();
            }
            case DIVIDE -> {
                if (secondNumber.doubleValue() == 0) {
                    throw new ArithmeticException("0으로 나눌 수 없습니다.");
                }
                this.answers.add(firstNumber.doubleValue() / secondNumber.doubleValue());
                return firstNumber.doubleValue() / secondNumber.doubleValue();
            }
            default -> throw new UnsupportedOperationException("지원되지 않는 연산자입니다.");
        }
    }
```

#### 3.3.2.1. `parseNumber()` 메소드

이 메소드는 공통되는 로직을 따로 분리하기 위해 생성하신 메소드로 보입니다.
리팩토링의 시작은 공통되는, 중복되는 코드를 없애는 것이므로 아주 좋은 리팩토링입니다.
여기서 조금 더 개선할 수 있는 포인트는 메소드의 `접근 제어자`입니다.

이 메소드는 `App` 클래스 내부에서만 사용되는 메소드이므로 안전하게 `private`으로 수정하면 더 좋습니다.
참고로 `main()` 메소드가 항상 `public`이어야 하는 이유는 Java 프로그램의 시작점은 `main()` 메소드이므로 외부에서 호출되기 때문입니다.

한가지 더 말씀드리자면, 메소드가 `null`을 리턴하게 되면 [이 메소드의 호출하는 부분에서 항상 `null`을 체크해줘야 합니다.](https://github.com/alsqja/Java-calculator/blob/d78e3c8b35358026242f82b1341a0db7e9a6d15b/src/lv3/App.java#L68-L75)
반드시 `null`을 리턴해줘야 하는 경우가 아니라면, `Exception`을 던져서 호출하는 부분에서 `try-catch`로 처리하도록 두는 것이 가장 좋습니다.
`null`을 리턴하는 것은 `null` 처리에 대한 책임을 호출자에게 넘기게 됩니다.

- `parseNumber()` 메소드
  ```java
    public static Number parseNumber(String input) throws NumberFormatException {
        // try-catch를 지우고 삼항연산자로 간단하게 바꿨습니다.
        return input.contains(".")
            ? Double.parseDouble(input)
            : Integer.parseInt(input);
    }
  ```
- `parseNumber()` 메소드 호출 부분
  ```java
            Number firstNumber;
            Number secondNumber;

            try {
                // 입력된 값이 정수인지 실수인지 판별하여 적절한 타입 선택
                firstNumber = parseNumber(firstInput);
                secondNumber = parseNumber(secondInput);
            } catch (NumberFormatException e) {
                System.out.println("잘못된 숫자 입력입니다.");
                return;
            }
  ```

#### 3.3.2.2. 명령어에 해당하는 문자열

"exit", "bigger", "calc", "get", "set", "delete"처럼 하드코딩된 이 문자열들은 프로그램의 커맨드로 사용되고 있습니다.
우리는 연산자를 쉽게 활용하도록 `OperType`이라는 enum 클래스를 생성한 기억이 있습니다.
이와 마찬가지로 위 문자열들은 enum 클래스로 만들면 더욱 편하게 관리할 수 있습니다!

----

# 4. 클린 코드

민범님께서는 코드 컨벤션을 잘 지켜주고 계십니다. 또한 변수, 메소드, 파라미터 등의 이름 또한 이름만 봐도 역할을 알 수 있게 직관적인 이름으로 지어주고 있습니다.
다만, 위에서 많이 언급했듯이 코드를 조금 더 읽기 쉬운 코드로 작성한다면 동료 개발자들이 같이 일하고 싶은 개발자가 되실 것 같습니다.

개발자의 개발 과정은 "코드를 작성하는 시간은 10%고, 코드를 읽는 시간이 90%다"라는 말이 있습니다. 이것은 유지보수와 관련이 있습니다.
만약 10명의 인원으로 구성된 개발팀에서 일하고 있다고 가정합시다. 단순 계산으로 내가 작성한 코드가 10%, 팀원들이 작성한 코드가 90%가 됩니다.
프로젝트를 유지보수하기 위해서는 당연히 팀원들이 작성한 코드도 이해하고 있어야 합니다. 이렇게 생각해보면 내가 코드를 작성하는 시간보다 코드를 읽는 시간이 더 많다는 것에 동의하실 것 같습니다.

여기서 효율을 높이려면 개발자들의 코드 읽는 시간을 줄여야 합니다. 나도 다른 개발자들의 코드를 읽지만, 다른 개발자들 또한 나의 코드를 읽고 분석하고 있습니다.
그래서 읽기 쉬운 코드를 작성해야 하고, 여기서 나온 패러다임이 바로 "`클린 코드`"입니다.
`클린 코드`에 대한 모든 것을 알아야 하는 것은 아니지만, 관심이 있으시다면 [이 아티클](https://yozm.wishket.com/magazine/detail/2415/)을 읽어보시면 좋을 것 같습니다.
변수나 메소드의 이름, 코드의 묶음, 위치 등이 모두 `클린 코드`와 관련이 있답니다.

**Comment by alsqja** [comment]
피드백 반영 후 수정 완료 했습니다.
추후 Enum 관련 수정도 공부 후 업데이트 예정입니다.
